; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ServiceSample"
#define MyAppVersion "1.0.1"
#define MyAppPublisher "Lê Xuân Tuấn Anh"
#define MyAppURL "https://github.com/z-pc"
#define MyAppExeName "app_services.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{70C67E35-8B0A-48AE-98F8-E0726E2A243E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename={#MyAppName}_setup_{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
UsePreviousAppDir=False
WizardImageFile=image.bmp
WizardSmallImageFile=icon.bmp
LicenseFile=License.rtf
SetupIconFile=icon.ico
UsePreviousGroup=False
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "..\build\Release\app_services.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\Release\config.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\Release\fmt.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\Release\spdlog.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "install_service.ps1"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
    

[Run]
Filename: "powershell.exe"; \
    Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\\install_service.ps1"""; \
    Flags: waituntilterminated runhidden

[UninstallRun]
Filename: "powershell.exe"; \
    Parameters: "-ExecutionPolicy Bypass -Command ""Stop-Service -Name '{#MyAppName}' -Force -ErrorAction SilentlyContinue; sc.exe delete '{#MyAppName}' | Out-Null"""; \
    Flags: runhidden waituntilterminated
Filename: "powershell.exe"; \
    Parameters: "-ExecutionPolicy Bypass -Command ""Get-NetFirewallRule -DisplayName '{#MyAppName} (TCP)' -ErrorAction SilentlyContinue | Remove-NetFirewallRule"""; \
    Flags: waituntilterminated runhidden

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
